### ISSUE TITLE
No DBConfig.json file

### ISSUE THREAD

**Issue by DoqtorKirby** [PassiveModding/ELO_Bot#13]
```
Unhandled Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Saitama\Downloads\Tsukuyomi\ELO\setup\DBConfig.json'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at ELO.Handlers.DatabaseHandler..ctor() in C:\Users\Saitama\Downloads\Tsukuyomi\ELO\Handlers\DatabaseHandler.cs:line 62
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCreateInstance(CreateInstanceCallSite createInstanceCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)

   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at ELO.Program.StartAsync() in C:\Users\Saitama\Downloads\Tsukuyomi\ELO\Program.cs:line 66
   at ELO.Program.Main(String[] args) in C:\Users\Saitama\Downloads\Tsukuyomi\ELO\Program.cs:line 36
```

**Comment by DoqtorKirby** [comment]
This is compiled from VS2017. A similar result (different file path) results from using the build bats.

**Comment by Luupy** [comment]
i have this problem too
